name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'  # Using Node 16.x to avoid deprecated Node 12 issues

      - name: Install dependencies
        run: npm install  # This will install all dependencies in package.json

      - name: Run the blog generator
        run: python blog_generator.py  # Make sure this points to your script


    # Add additional steps as required, like testing, building, or deploying
